name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    if: contains(github.event.head_commit.message, 'v[0-9]+\.[0-9]+\.[0-9]+')
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Get commit message
        id: commit_message
        run: echo ::set-output name=MESSAGE::$(git log --format=%B -n 1 $GITHUB_SHA)

      - name: Extract version from commit message
        id: extract_version
        run: echo ::set-output name=VERSION::$(echo ${{ steps.commit_message.outputs.MESSAGE }} | grep -o -E 'v[0-9]+\.[0-9]+\.[0-9]+')

      - name: Build and tag Docker image
        run: |
          docker buildx build --push --tag januszadlo/jellyfin-exporter:${{ steps.extract_version.outputs.VERSION }} .
