name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub 
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Get commit message
        id: commit_message
        run: echo ::set-output name=MESSAGE::$(git log --format=%B -n 1 $GITHUB_SHA)

      - name: Extract version from commit message
        id: extract_version
        run: |
          COMMIT_MESSAGE=$(git log --format=%B -n 1 $GITHUB_SHA)
          VERSION_REGEX="v[0-9]+\.[0-9]+\.[0-9]+"
          if [[ $COMMIT_MESSAGE =~ $VERSION_REGEX ]]; then
            echo "::set-output name=VERSION::${BASH_REMATCH[0]}"
          else
            echo "No version found in commit message. Skipping build and push steps."
            exit 0
          fi

      - name: Build and tag Docker image
        run: |
          docker buildx build --push --tag januszadlo/jellyplexporter:${{ steps.extract_version.outputs.VERSION }} .
